### ISSUE TITLE
Nil value for npcID in Molten Core

### ISSUE THREAD

**Issue by wardz** [rgd87/LibClassicCasterino#13]
Forwarding this error from a Curseforge comment:

> The lib causes errors in MC:
> 
> ```
> Message: ...ils\Libs\LibClassicCasterino\LibClassicCasterino.lua:74: attempt to concatenate local 'npcID' (a nil value)
> Time: Thu Sep 19 20:44:28 2019
> Count: 3
> Stack: ...ils\Libs\LibClassicCasterino\LibClassicCasterino.lua:74: attempt to concatenate local 'npcID' (a nil value)
> ...ils\Libs\LibClassicCasterino\LibClassicCasterino.lua:74: in function <...ils\Libs\LibClassicCasterino\LibClassicCasterino.lua:72>
> ...ils\Libs\LibClassicCasterino\LibClassicCasterino.lua:142: in function <...ils\Libs\LibClassicCasterino\LibClassicCasterino.lua:124>
> (tail call): ?
> 
> Locals: guid = "Player-4440-0025767F"
> spellName = "Wrath"
> _ = "Player"
> _ = "4440"
> _ = "0025767F"
> _ = nil
> _ = nil
> npcID = nil
> (*temporary) = nil
> (*temporary) = "Wrath"
> (*temporary) = "attempt to concatenate local 'npcID' (a nil value)"
> ```
> 
> ```
> Message: ...ils\Libs\LibClassicCasterino\LibClassicCasterino.lua:74: attempt to concatenate local 'npcID' (a nil value)
> Time: Thu Sep 19 20:44:36 2019
> Count: 8
> Stack: ...ils\Libs\LibClassicCasterino\LibClassicCasterino.lua:74: attempt to concatenate local 'npcID' (a nil value)
> ...ils\Libs\LibClassicCasterino\LibClassicCasterino.lua:74: in function <...ils\Libs\LibClassicCasterino\LibClassicCasterino.lua:72>
> ...ils\Libs\LibClassicCasterino\LibClassicCasterino.lua:165: in function <...ils\Libs\LibClassicCasterino\LibClassicCasterino.lua:124>
> (tail call): ?
> 
> Locals: guid = "Player-4440-0018C2CA"
> spellName = "Adrenaline Rush"
> _ = "Player"
> _ = "4440"
> _ = "0018C2CA"
> _ = nil
> _ = nil
> npcID = nil
> (*temporary) = nil
> (*temporary) = "Adrenaline Rush"
> (*temporary) = "attempt to concatenate local 'npcID' (a nil value)"
> ```

**Comment by d87** [comment]
That's been fixed a long time ago.
