### ISSUE TITLE
your GetUnitSpeed "hack" isnt working

### ISSUE THREAD

**Issue by bgfds** [rgd87/LibClassicCasterino#18]
not working at all, while other addons have it working perfectly

**Comment by d87** [comment]
it's not supposed to work on friendly players

**Comment by bgfds** [comment]
I'm testing on my own enemy faction char and it's not working at all

**Comment by bgfds** [comment]
I'm trying to make a WA with an icon for casts because I don't like castbars and only care about a few specific casts anyways and yea movement isn't causing it to deactive, maybe thats on WA's end?

**Comment by d87** [comment]
I don't know, it was reportedly working. I don't have a handy enemy faction char or even a sub right now to check

**Comment by bgfds** [comment]
do you have discord? i can show you it not working/test fixes etc when u have time 

really want it to work lol

**Comment by d87** [comment]
Install https://github.com/rgd87/NugCast/releases
Check if it's working there

**Comment by d87** [comment]
d87#2519
