### ISSUE TITLE
Support casting speed slows, and CC interruptions

### ISSUE THREAD

**Issue by ascott18** [rgd87/LibClassicCasterino#2]
ClassicCastbars supports both of these things, and it would great if this did too.

https://github.com/wardz/ClassicCastbars/blob/master/ClassicCastbars/core/Data.lua#L1350

Edit: I see it already supports two effects, but there are many more.

**Comment by d87** [comment]
I think CoT and Mind-numbing is enough. the rest of them are some obscure pve slows that are applied once in a blue moon to friendly targets in instances. No one cares about friendly casts.

I kinda forgot about CC interruption thing, will add it

**Comment by d87** [comment]
Ok, CC interruptions are in
