### ISSUE TITLE
UNIT_CAST_FAILED instead of UNIT_CAST_INTERRUPTED

### ISSUE THREAD

**Issue by mrbuds** [rgd87/LibClassicCasterino#20]
At the following 2 lines, UNIT_SPELLCAST_FAILED callback is sent where i think it should be UNIT_SPELLCAST_INTERRUPTED

https://github.com/rgd87/LibClassicCasterino/blob/762353ab564e56c4f209da6c680ab6627110eee6/LibClassicCasterino.lua#L709
https://github.com/rgd87/LibClassicCasterino/blob/762353ab564e56c4f209da6c680ab6627110eee6/LibClassicCasterino.lua#L223

On retail UNIT_SPELLCAST_FAILED event is sent when you spam the key of a cast that is already in progress, which does not stop the cast bar.
From my tests this does not happen on classic, but for compatibility i'd prefer not stop the display of the cast bar when UNIT_SPELLCAST_FAILED is fired.

Could you make UNIT_DIED and the "Cast Interruption Checker" fire UNIT_SPELLCAST_INTERRUPTED ?

**Comment by d87** [comment]
Done
