### ISSUE TITLE
Cast Interruption Checker wrongly invalidating casts due to lag

### ISSUE THREAD

**Issue by mrbuds** [rgd87/LibClassicCasterino#21]
Hello, we had a bug report for weakauras about spells not showing after a move https://github.com/WeakAuras/WeakAuras2/issues/1774

You can see the result of the bug here https://streamable.com/20zi7

When i first checked the differences between the addon ClassicCastBars and your implementation i noticed wardz accounted for a 0.25s lag for the move check before canceling enemy cast.

So i tested in a duel with a friend and i could reproduce the issue, with him casting hearthstone between moves. And then i tested with a modification to your lib accounting for a 0.25s lag, and this change seemed to fix the issue for me.

```Lua
    f:SetScript("OnUpdate", function(self, elapsed)
        local guid, timeout = next(movecheckGUIDs)
        while guid ~= nil do
            -- Removing while iterating here, but it doesn't matter
            local timeStart = MOVECHECK_TIMEOUT - (timeout - elapsed)
            if timeStart > 0.25 then
                local unit = GetUnitForFreshGUID(guid)
                if unit then
                    if GetUnitSpeed(unit) ~= 0 then
                        CastStop(guid, nil, "INTERRUPTED")
                        movecheckGUIDs[guid] = nil
                        return
                    end
                end
            end
```

**Comment by d87** [comment]
I see, fixed it
