### ISSUE TITLE
Incorrect cast bars for ElvUI

### ISSUE THREAD

**Issue by Polopollo85** [rgd87/LibClassicCasterino#22]
Hello, an Elvui support member redirected me to your project. 

I often encounter super fast cast bars, for instance here:
https://www.youtube.com/watch?v=m5nYLlqZuGI&vq=hd1080

You can see it seems done, while behind, it was ~70% done before I interrupted.

**Comment by d87** [comment]
library doesn't know all npc cast times in the game, it's measuring the first successful cast, until then 1.5s is the default duration

**Comment by Polopollo85** [comment]
Weird, I farm here like almost every morning and it still doesn't fix the duration. How does it work to fix it?

**Comment by d87** [comment]
i just told yout how it works, but durations aren't saved benween sessions. Let mob complete a single cast

**Comment by Polopollo85** [comment]
oh ill will try to let the cast finish then ill exit and restart the game then. Thanks!

**Comment by d87** [comment]
What? Durations ARE NOT saved betweed logins

**Comment by Polopollo85** [comment]
What do you call session?

**Comment by d87** [comment]
from login to logout

**Comment by Polopollo85** [comment]
Oops sorry I misread, I read that it was saved between sessions.

So does it mean that i let a mob complete a full cast, then if I restart the game, the information...is lost?

**Comment by d87** [comment]
yes

**Comment by Polopollo85** [comment]
Ok then it means this cast will never be right for 99% of the cases... :/
