### ISSUE TITLE
Aimed shot doesn't cancel

### ISSUE THREAD

**Issue by Bowtems** [rgd87/LibClassicCasterino#23]
![Aimed shot](https://user-images.githubusercontent.com/54860906/67605045-17216200-f732-11e9-8d9f-6c715e9110a5.gif)
When casting Aimed shot as of it being added to the library, if I move or cancel it manually the cast bar continues until finished. Also I dont know if its possible for the cast bar to reflect haste, but it currently is not.

Example of it happening:
https://imgur.com/P2l2cYy

**Comment by d87** [comment]
I added Rapid Fire and stuff in the latest update.
The canceling is just unreliable like that, it can't be better that it is
But still movement should cancel cast if done after 0.25s delay
And ESC just doesn't cancel unless you do it in the later part of the cast.
