### ISSUE TITLE
[BUG] FakeCasting still display as spell cast applied

### ISSUE THREAD

**Issue by cordankos** [rgd87/LibClassicCasterino#3]
I created 1 level Paladin and use "target" as unitID to check yourself on casting Holy Light and I fake casting it to cause this bug, I have visual bar which works by callbacks and they are properly react however seems CLEU is little bit bug with exactly fake casting, sometimes it's react on fake casting properly, sometimes no. I see how cast bar remain going to be 0 when I totally haven't casting Holy Light.

**Comment by d87** [comment]
I'm not sure what you mean by fake casting, but If you cancel cast immediately after starting CAST_FAILED event just won't appear in combat log and cast bar will continue until completion. Nothing i can do about it

**Comment by cordankos** [comment]
Yes, I think I experience this issue which you described

**Comment by cordankos** [comment]
UNIT_SPELLCAST_STOP this event works properly when CAST_FAILED doesn't appear, I think it's great tweak for your lib to add through this event CastStop if CLEU failed, not for all units but still better than nothing, right? :)

**Comment by d87** [comment]
UNIT_SPELLCAST_STOP is only for player, if ti was that easy we wouldn't need any of this

**Comment by cordankos** [comment]
Oh yea, I checking yourself what's why. Might is it do able through animation check? No idea if it's possible on lua

**Comment by cordankos** [comment]
What about to add OnUpdate function which will pairs all nameplates around you and target with party and raid members for check on GetUnitSpeed with update interval 0 by their GUID? If unit inside 'casters' table and he moved then CastStop

**Comment by d87** [comment]
that can work actually

**Comment by d87** [comment]
Ok, it's in now, but only for enemy players. So targeting yourself won't work

**Comment by cordankos** [comment]
You already have 'casters' table which becomes nil for GUIDs as soon as they do not cast anything, don't know a point to use additional table. You use nameplates but on bg it will not be enough since distance is limited to 20 yards, you have to pairs through all arena unitID as well :) Anyway I released that on my own code before you posted commit, my idea works indeed great, I use first common units (since nameplates can be off) then nameplates (only enemies and outside bg) + arena (only at bg) + raid / party (depended on group or if solo then skip). Friendly nameplates can be turned off and then they will not work at all on event NAMEPLATE_ADDED, so better to use is a pairs through current group type party / raid. Finally, we have parsed all available guids to compare. This thing works as long as enemy player don't use /stopcasting macro by the way and.. until that person starts lags :D (I mean when unit moving with casting bar while at server side his current speed is 0 but we still will receive it as not 0, so funny thing huh)

**Comment by cordankos** [comment]
Btw, in commons units missed "mouseover" unitID

**Comment by cordankos** [comment]
I prefer to leave tracking of movement interrupt for any unit because I plan to use it in raid where will need to know info about incomingheal and resurrection, so don't skip it for friendly players
