### ISSUE TITLE
TalentDecreased only used for channeling spells

### ISSUE THREAD

**Issue by leothlon** [rgd87/LibClassicCasterino#30]
inside "if castType == "CHANNEL" then" on row 93 there is this:
    local decreased = talentDecreased[spellID]
    if decreased then
        castTime = castTime - decreased
    end

i think that should be moved below the if so it works on all spells, this will always show the shortest possible casttime on spells.

Atleast personaly i would rather have the castbar end to fast than to slow..
or you could add an option for the user to specify if they want the untalented or talented casttimes...

**Comment by d87** [comment]
Yeah, that was a bug. Thanks for reporting
