### ISSUE TITLE
Castspeed with debuff

### ISSUE THREAD

**Issue by leothlon** [rgd87/LibClassicCasterino#31]
Hi,
If a warlock casts curse of tongues on me (60% slower cast) then starts to cast fear the fear is displayd as 2.4s instead of its actual 1.5s.
So it seems that if i have a castspeed debuff on me then it is counted on other targets aswell even if they have normal castspeed.

why is it checking me for castspeed modifiers when its not my casts beeing shown?

**Comment by d87** [comment]
> why is it checking me for castspeed modifiers when its not my casts beeing shown?

It's not, CoT on player is never even touched, so idk

**Comment by leothlon** [comment]
For some reason it does tho, because i even saved a vod of it to go back and see what happened and thats when i saw it showd fear casttime as 2.4s instead of 1.5

And then i checked the code to see if it was wrong but it correctly say 1.5s, i checked vod again and saw that wlock had casted CoT on me prior to the fear, and as 1.5*1.6 = 2.4 i draw the conclusion that the CoT on me is added to the casts of my target

**Comment by d87** [comment]
https://github.com/rgd87/LibClassicCasterino/blob/master/LibClassicCasterino.lua#L297
This is the only place where CoT is checked, and it'll never even reach that place with "player" as a unit.
I don't have any warlock friends to check, or a sub even. My best guess is that you're using ClassicCastbars, that's how impossible it seems.

**Comment by leothlon** [comment]
I'm using ElvUi and they use "libClassicCasteriono-1.0"
Been looking at their code for the castbars and cant find anything that would affect this either tbh.

But yea, looking at your code it does seem like it should not be like this, my only guess is that somehow you get to that point with the wrong srcUnit info somehow.

Or that ElvUi is implementing the library wrongly, but cant see to find how or where that would be.

**Comment by d87** [comment]
Try doing ```/dump GetSpellInfo(5782)``` when with CoT, 4th return value should be the cast time, maybe it's changing depending on whether player himself has reduced cast speed

**Comment by d87** [comment]
Yeah, that's probably it, on live it does change depending on player haste

**Comment by d87** [comment]
Ok, fixed
