### ISSUE TITLE
About Swing Timer

### ISSUE THREAD

**Issue by yaoye** [rgd87/LibClassicCasterino#39]
Hi, guys,

Thanks for the awesome lib.

I'm a newbie and got a question, how to get main hand, off hand, and ranged swing timer of player?

Thanks a lot.

**Comment by d87** [comment]
Enemy player? You can't. And measuring it from combat log would be all sorts of inaccurate
For player as in yourself i'm not sure what is the best way, check how swing timer addons do it
Anyway, this library is not dealing with swing timers
