### ISSUE TITLE
Event for CC interrupted spells

### ISSUE THREAD

**Issue by Backupiseasy** [rgd87/LibClassicCasterino#4]
When a cast is interrupted by a CC spell - something you added recently which is nice - the event that is fired after that is UNIT_SPELLCAST_CHANNEL_STOP, not, what would make more sense, UNIT_SPELLCAST_INTERRUPTED or maybe UNIT_SPELLCAST_FAILED (which the line CastStop(dstGUID, nil, "FAILED") would suggest, but as the second parameter is nil, UNIT_SPELLCAST_CHANNEL_STOP will be fired. I can't test it right now, but I think it is that way. 
What is the reasoning behind this?

**Comment by d87** [comment]
CastStop(dstGUID, nil, "FAILED") makes UNIT_SPELLCAST_FAILED
second arg being nil means unspecified cast type

**Comment by Backupiseasy** [comment]
You are right. No idea why I did not see that. Still, to fire an UNIT_SPELLCAST_FAILED here, does not allow it for see if it's a stunned unit or a unit that cancel it's cast, right? Not sure though when this event is actually fired...

**Comment by d87** [comment]
I'm pretty sure on live if stunned it would be either FAILED of just STOP, not INTERRUPTED.

**Comment by d87** [comment]
Just checked, on live it's actually doing all 3 events at once lol
UNIT_SPELLCAST_INTERRUPTED
UNIT_SPELLCAST_STOP
UNIT_SPELLCAST_FAILED_QUIET

**Comment by Backupiseasy** [comment]
That is funny. I always thought that on live, if you stun a casting mob, you don't get any UNIT_SPELLCAST event ... that's why detection this is solved with monitoring UNIT_AURA_APPLIED, e.g., in NeatPlates. But I never really looked into it in more detail - that's why TP on live doesn't show stuns as interrupts.

**Comment by d87** [comment]
I changed it to INTERRUPTED btw
