### ISSUE TITLE
1.14 Compatibility

### ISSUE THREAD

**Issue by Aviana** [rgd87/LibClassicCasterino#41]
The 1.14 patch removed the return value "notInterruptible" from CastingInfo and UnitCastingInfo.
This
https://github.com/rgd87/LibClassicCasterino/blob/3f34e6260aab7d8fd921887dc01cf3c603bf7227/LibClassicCasterino.lua#L365
needs to be
`            return name, nil, icon, startTimeMS, endTimeMS, nil, castID, spellID`

**Comment by d87** [comment]
Thanks, fixed

**Comment by Aviana** [comment]
I am sorry to bother again but blizzard seems to have changed their mind on this one. This change needs to be reverted now.
https://github.com/Stanzilla/WoWUIBugs/issues/184#issuecomment-962625854

**Comment by d87** [comment]
Done
