### ISSUE TITLE
Inaccurate cast durations

### ISSUE THREAD

**Issue by nyyr** [rgd87/LibClassicCasterino#5]
First of all: Thanks for the Lib, this really helps ;-)

I'm not sure whether this is a limitation of WoW Classic or if this is a miscalculation in LibClassicCasterino: A level 1 Shaman's Healing Wave cast time is 1.5secs. When targeting yourself and using LibClassicCasterino to show the target's spellcast, it returns 3 seconds (endTime - startTime).

Is this a bug? Or do we have to live with such discrepancies?

**Comment by d87** [comment]
Yes, it can't discern ranks
