### ISSUE TITLE
UnitCastingInfo: startTime is nil after SPELL_CAST_START

### ISSUE THREAD

**Issue by Backupiseasy** [rgd87/LibClassicCasterino#6]
Hey, 
as user of Threat Plates reported a Lua error related to a cast: https://www.curseforge.com/wow/addons/threat-plates-classic?comment=176
Basically, the error happens after calling UnitCastingInfo(unitid). What confuses me is that startTime never should be nil. If I read your code correctly, it's initialized with GetTime() and not really changed. So I am a bit clueless why this happens.
The whole trace starts after a SPELL_CAST_START event in LibClassicCasterino, so why could startTime be nil?
The line numbers might be a little bit off as I made some changes to your lib to pass some additional information when a cast is interrupted.

**Comment by d87** [comment]
idk, the only way it would be nil is if the whole cast or unit leading to it was removed in some race condition.

Judging by this https://github.com/oUF-wow/oUF/blob/master/elements/castbar.lua#L112 even live is having these problems.

**Comment by Backupiseasy** [comment]
Interesting ... never had this issue myself, but easy to workaround then. Thanks for your help.
