### ISSUE TITLE
Suggestion: Use AURA_APPLIED+crown control spells list to detect cast interrupts.

### ISSUE THREAD

**Issue by michaelnpsp** [rgd87/LibClassicCasterino#7]
I suggest to use SPELL_AURA_APPLIED event to detected crown control auras applied to enemy units, and in this case call CastStop()  if necesssary  (If the enemy was sheeped/stunned/etc is obvious the his cast has been interrupted).
Crown control spell list (GSI = GetSpellInfo):

`
-- crow control spells
local ccSpells = {
    [GSI(5211)] = true,       -- Bash
    [GSI(24394)] = true,      -- Intimidation
    [GSI(853)] = true,        -- Hammer of Justice
    [GSI(22703)] = true,      -- Inferno Effect (Summon Infernal)
    [GSI(408)] = true,        -- Kidney Shot
    [GSI(12809)] = true,      -- Concussion Blow
    [GSI(20253)] = true,      -- Intercept Stun
    [GSI(20549)] = true,      -- War Stomp
    [GSI(2637)] = true,       -- Hibernate
    [GSI(3355)] = true,       -- Freezing Trap
    [GSI(19386)] = true,      -- Wyvern Sting
    [GSI(118)] = true,        -- Polymorph
    [GSI(28271)] = true,      -- Polymorph: Turtle
    [GSI(28272)] = true,      -- Polymorph: Pig
    [GSI(20066)] = true,      -- Repentance
    [GSI(1776)] = true,       -- Gouge
    [GSI(6770)] = true,       -- Sap
    [GSI(1513)] = true,       -- Scare Beast
    [GSI(8122)] = true,       -- Psychic Scream
    [GSI(2094)] = true,       -- Blind
    [GSI(5782)] = true,       -- Fear
    [GSI(5484)] = true,       -- Howl of Terror
    [GSI(6358)] = true,       -- Seduction
    [GSI(5246)] = true,       -- Intimidating Shout
    [GSI(6789)] = true,       -- Death Coil
    [GSI(9005)] = true,       -- Pounce
    [GSI(1833)] = true,       -- Cheap Shot
    [GSI(16922)] = true,      -- Improved Starfire
    [GSI(19410)] = true,      -- Improved Concussive Shot
    [GSI(12355)] = true,      -- Impact
    [GSI(20170)] = true,      -- Seal of Justice Stun
    [GSI(15269)] = true,      -- Blackout
    [GSI(18093)] = true,      -- Pyroclasm
    [GSI(12798)] = true,      -- Revenge Stun
    [GSI(5530)] = true,       -- Mace Stun
    [GSI(19503)] = true,      -- Scatter Shot
    [GSI(605)] = true,        -- Mind Control
    [GSI(7922)] = true,       -- Charge Stun
    [GSI(18469)] = true,      -- Counterspell - Silenced
    [GSI(15487)] = true,      -- Silence
    [GSI(18425)] = true,      -- Kick - Silenced
    [GSI(24259)] = true,      -- Spell Lock
    [GSI(18498)] = true,      -- Shield Bash - Silenced
    [GSI(13327)] = true,      -- Reckless Charge
    [GSI(1090)] = true,       -- Sleep
    [GSI(5134)] = true,       -- Flash Bomb Fear
    [GSI(19821)] = true,      -- Arcane Bomb Silence
    [GSI(4068)] = true,       -- Iron Grenade
    [GSI(19769)] = true,      -- Thorium Grenade
    [GSI(13808)] = true,      -- M73 Frag Grenade
    [GSI(4069)] = true,       -- Big Iron Bomb
    [GSI(12543)] = true,      -- Hi-Explosive Bomb
    [GSI(4064)] = true,       -- Rough Copper Bomb
    [GSI(12421)] = true,      -- Mithril Frag Bomb
    [GSI(19784)] = true,      -- Dark Iron Bomb
    [GSI(4067)] = true,       -- Big Bronze Bomb
    [GSI(4066)] = true,       -- Small Bronze Bomb
    [GSI(4065)] = true,       -- Large Copper Bomb
    [GSI(13237)] = true,      -- Goblin Mortar
    [GSI(835)] = true,        -- Tidal Charm
    [GSI(13181)] = true,      -- Gnomish Mind Control Cap
    [GSI(12562)] = true,      -- The Big One
    [GSI(15283)] = true,      -- Stunning Blow (Weapon Proc)
    [GSI(56)] = true,         -- Stun (Weapon Proc)
    [GSI(26108)] = true,      -- Glimpse of Madness
}

`

**Comment by d87** [comment]
it's already doing that
