### ISSUE TITLE
Arcane Missiles channel event not triggering

### ISSUE THREAD

**Issue by fulzamoth** [rgd87/LibClassicCasterino#9]
If a player target casts Arcane Missiles it does not trigger a "SPELL_AURA_APPLIED" event and the channel goes undetected because the "SPELL_CAST_SUCCESS" event is ignored on the assumption that it's followed an aura. I've only tested with the one spell so far so don't know if others have the same issue or not. 

Cannibalize does apply the aura, so the event for it works.

**Comment by d87** [comment]
Should be fixed now
